### ISSUE TITLE
Gcompris flatpak, desktop menu category should be Education, not games.

### ISSUE THREAD

**Issue by cyberorg** [flathub/org.kde.gcompris#16]
Installing from flatpak puts the launcher under Games, please add it under Education as the normal deb package does.

**Comment by tsdgeos** [comment]
We don't modify the source code, so this is not a flatpak packaging bug.

**Comment by petitlapin** [comment]
Hi,

this is already the case in the source: https://invent.kde.org/education/gcompris/-/blob/master/org.kde.gcompris.desktop#L129 if I'm not wrong?
