### ISSUE TITLE
Language PT-BR does not work

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kde.gcompris#3]
![captura de tela de 2018-05-06 20-41-23](https://user-images.githubusercontent.com/26097419/39679047-3fe43c6e-516e-11e8-8067-61b7e5980c39.png)
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Unable to load translation for locale  "pt_PT" , use en_US by default
exeCount set to:  3
qml: enter main.qml (run #3, ratio=1.476923076923077, fontRatio=1.6, dpi=102, sharedWritablePath=/sysroot/home/leandro/.var/app/org.kde.gcompris/data/GCompris)
Downloading resource file "data2/voices-ogg/voices-pt.rcc"
Error downloading Contents from QUrl("http://gcompris.net/data2/voices-ogg/Contents") : QNetworkReply::NetworkError(HostNotFoundError) : "Host gcompris.net not found"
notifyShowLockedActivitiesChanged:  false
notifyAudioVoices:  true
notifyAudioEffects:  true
virtualkeyboard set to:  false
enableAutomaticDownloads set to:  true
c++ setSectionVisible= true
notifySectionVisible:  true
notifyWordset:  ""
new font:  "Andika-R.otf"
new fontLetterSpacing:  0
new locale:  "pt_BR.UTF-8"
save configuration for: ""
Downloading resource file "data2/voices-ogg/voices-pt_BR.rcc"
Error downloading Contents from QUrl("http://gcompris.net/data2/voices-ogg/Contents") : QNetworkReply::NetworkError(HostNotFoundError) : "Host gcompris.net not found"

**Comment by LeandroStanger** [comment]
@nedrichards How is the progress of the correction?

**Comment by petitlapin** [comment]
Hi,

it seems to be fixed with https://github.com/flathub/org.kde.gcompris/issues/4

**Comment by LeandroStanger** [comment]
Is still in English
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Unable to load translation for locale  "pt_BR" , use en_US by default
exeCount set to:  10
qml: enter main.qml (run #10, ratio=1.476923076923077, fontRatio=1.6, dpi=101, sharedWritablePath=/sysroot/home/leandro/.var/app/org.kde.gcompris/data/GCompris)
Downloading resource file "data2/voices-ogg/voices-pt_BR.rcc"
Local resource is up-to-date: "voices-pt_BR.rcc"
Successfully registered resource "/sysroot/home/leandro/.var/app/org.kde.gcompris/cache/KDE/gcompris-qt/data2/voices-ogg/voices-pt_BR.rcc"
notifyShowLockedActivitiesChanged:  false
notifyAudioVoices:  true
notifyAudioEffects:  true
virtualkeyboard set to:  false
enableAutomaticDownloads set to:  true
c++ setSectionVisible= true
notifySectionVisible:  true
notifyWordset:  ""
new font:  "Andika-R.otf"
new fontLetterSpacing:  0
save configuration for: ""
is bar hidden:  true
is bar hidden:  false
DownloadManager: shutting down, 0 active jobs
DownloadManager: shutting down, 0 active jobs
QCoreApplication::postEvent: Unexpected null receiver

```

**Comment by petitlapin** [comment]
These logs are not localized and will always be in English (it's for developers, not users). Is the content of the application translated?

**Comment by LeandroStanger** [comment]
@petitlapin não

**Comment by petitlapin** [comment]
@nedrichards hi, do you know if translations are retrieved for the compilation?
I'm not sure how flatpak work to get the source and compile ut globally in gcompris, what we do to build a package is:
cmake ...... (fill with the good folder and potentially options)
make getSvnTranslations -> this step retrieves the po files from kde (it's the one that I'm not sure it's done)
do the "normal" procedure with cmake and make to create the package.

**Comment by aleixpol** [comment]
To have translations I'd recommend using the tarballs:
http://gcompris.net/download/qt/src/gcompris-qt-0.91.tar.xz

flatpak-builder doesn't have network access.

**Comment by petitlapin** [comment]
@aleixpol thank you, how are linked this repo and https://cgit.kde.org/flatpak-kde-applications.git/tree/org.kde.gcompris.json ? Should I do a fix on kde repo and a PR here?

**Comment by aleixpol** [comment]
They are not related. You can just fix it here.

For the flatpak-kde-applications repository we just have nightlies so we'll need to have a different solution.
